ProjetoIntegrador/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# construtor geral das minhas urls
urlpatterns = [
	# por padrao um administrador
	# adionado chamada para a url do Sistema
    url(r'^admin/', admin.site.urls),
    url(r'', include('SistemaProgressao.urls', namespace='SistemaProgressao', app_name='SistemaProgressao')),
]

SistemaProgressao/urls.py
from django.conf.urls import url
from . import views

# definindo a chamada da view, o arquivo HTML
urlpatterns = [
	url(r'^$', views.apresentacao),

	url(r'^cadastrar/', views.cadastrar, name='cadastrar'),
	url(r'^login/', views.do_login, name='login'),
	url(r'^logout/', views.do_logout, name='logout'),

	url(r'^documents/$', views.documents),
	url(r'^infogerais/$', views.infogerais),
	url(r'^main/', views.main),
	url(r'^historico/$', views.historico),
	url(r'^anexoi/$', views.anexoi),
	url(r'^anexoii/$', views.anexoii),
	url(r'^anexoiii/$', views.anexoiii),
	url(r'^anexoiv/$', views.anexoiv),
	url(r'^apresentacao/$', views.apresentacao),

	url(r'^change_password/$', views.change_password, name='change_password'),
]

SistemaProgressao/models.py
from django.db import models
from django.contrib.auth.models import User

"""
# redefinir os anexos
"""

# classe usuario
class Usuario(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	
	def __str__ (self):
		return self.user.first_name

# classe dos documentos enviados pelos usuarios
class Documento(models.Model):
	link_pdf = models.FileField(upload_to=None, max_length=255)
	fk_usuario = models.ForeignKey(Usuario)

# classe do historico de movimentacao do usuario
class Historico(models.Model):
	# docsfinal/ é o diretorio para os arquivos
	link_pdf_final = models.FileField(upload_to='documents/', max_length=255)
	fk_usuario = models.ForeignKey(Usuario)


#
# desenvolvimentos dos formularios baseados no anexos I, II, III e IV
#

# informacoes gerais que todos os anexos vao possuir
class InfoGerais(models.Model):
	usuario = models.ForeignKey(Usuario)
	lotacao = models.CharField(max_length=15)
	classe = models.CharField(max_length=15)
	periodo = models.DateField()

	# retorna tudo
	def preenchimento(self):
		return self.usuario, self.lotacao, self.classe, self.periodo

class AnexoI(models.Model):
	# incluir os valores do arquivo excel enviado pelo flavio
	# anexo i

	### INICIO EIXO 1 ###
	# avaliacao discente
	eixo_1 = models.FloatField('Eixo 1')
	eixo_1_justificacao_comentario = models.TextField('Justificativa/Comentario')

	### INICIO EIXO 2.1 ###
	# atividades de ensino e apoio ao ensino
	# ensino convencional

	# horas de aula (media do per)/semana
	eixo_2_1_a_hora = models.FloatField()
	eixo_2_1_b_hora = models.FloatField()
	eixo_2_1_c_hora = models.FloatField()

	# pontos por hora de aula por semana
	eixo_2_1_a_pontos = models.FloatField()
	eixo_2_1_b_pontos = models.FloatField()
	eixo_2_1_c_pontos = models.FloatField()

	# total pontuacao
	eixo_2_1_a_total = models.FloatField()
	eixo_2_1_b_total = models.FloatField()
	eixo_2_1_c_total = models.FloatField()

	### INICIO EIXO 2.2 ###
	# orientacao de alunos

	# numero
	eixo_2_2_a_num = models.FloatField()
	eixo_2_2_b_num = models.FloatField()
	eixo_2_2_c_num = models.FloatField()
	eixo_2_2_d_num = models.FloatField()
	eixo_2_2_e_num = models.FloatField()
	eixo_2_2_f_num = models.FloatField()
	eixo_2_2_g_num = models.FloatField()
	eixo_2_2_h_num = models.FloatField()
	eixo_2_2_i_num = models.FloatField()
	eixo_2_2_j_num = models.FloatField()
	eixo_2_2_k_num = models.FloatField()

	# pontos por aluno por mes
	eixo_2_2_a_pontos = models.FloatField()
	eixo_2_2_b_pontos = models.FloatField()
	eixo_2_2_c_pontos = models.FloatField()
	eixo_2_2_d_pontos = models.FloatField()
	eixo_2_2_e_pontos = models.FloatField()
	eixo_2_2_f_pontos = models.FloatField()
	eixo_2_2_g_pontos = models.FloatField()
	eixo_2_2_h_pontos = models.FloatField()
	eixo_2_2_i_pontos = models.FloatField()
	eixo_2_2_j_pontos = models.FloatField()
	eixo_2_2_k_pontos = models.FloatField()

	# total
	eixo_2_2_a_total = models.FloatField()
	eixo_2_2_b_total = models.FloatField()
	eixo_2_2_c_total = models.FloatField()
	eixo_2_2_d_total = models.FloatField()
	eixo_2_2_e_total = models.FloatField()
	eixo_2_2_f_total = models.FloatField()
	eixo_2_2_g_total = models.FloatField()
	eixo_2_2_h_total = models.FloatField()
	eixo_2_2_i_total = models.FloatField()
	eixo_2_2_j_total = models.FloatField()
	eixo_2_2_k_total = models.FloatField()

	### INICIO EIXO 2.3 ###
	# participacao em projetos, bancas, comissoes, conselhos e equivalentes

	# numero
	eixo_2_3_a_num = models.FloatField()
	eixo_2_3_b_num = models.FloatField()
	eixo_2_3_c_num = models.FloatField()
	eixo_2_3_d_num = models.FloatField()
	eixo_2_3_e_num = models.FloatField()
	eixo_2_3_f_num = models.FloatField()
	eixo_2_3_g_num = models.FloatField()
	eixo_2_3_h_num = models.FloatField()

	# pontos por participacao
	eixo_2_3_a_pontos = models.FloatField()
	eixo_2_3_b_pontos = models.FloatField()
	eixo_2_3_c_pontos = models.FloatField()
	eixo_2_3_d_pontos = models.FloatField()
	eixo_2_3_e_pontos = models.FloatField()
	eixo_2_3_f_pontos = models.FloatField()
	eixo_2_3_g_pontos = models.FloatField()
	eixo_2_3_h_pontos = models.FloatField()

	# total
	eixo_2_3_a_total = models.FloatField()
	eixo_2_3_b_total = models.FloatField()
	eixo_2_3_c_total = models.FloatField()
	eixo_2_3_d_total = models.FloatField()
	eixo_2_3_e_total = models.FloatField()
	eixo_2_3_f_total = models.FloatField()
	eixo_2_3_g_total = models.FloatField()
	eixo_2_3_h_total = models.FloatField()

	### INICIO EIXO 2.4 ###
	# participacao em reunioes e cumprimentos de prazos

	# numero
	eixo_2_4_a_num = models.FloatField()
	eixo_2_4_b_num = models.FloatField()

	# pontos
	eixo_2_4_a_pontos = models.FloatField()
	eixo_2_4_b_pontos = models.FloatField()

	# total
	eixo_2_4_a_total = models.FloatField()
	eixo_2_4_b_total = models.FloatField()

	# justificativa / comentario
	eixo_2_justificacao_comentario = models.TextField()

	### INICIO EIXO 3.1 ###
	# atividades de capacitacao
	# participacao em cursos e aprovacao em disciplinas

	# numero
	eixo_3_1_a_num = models.FloatField()
	eixo_3_1_b_num = models.FloatField()
	eixo_3_1_c_num = models.FloatField()
	eixo_3_1_d_num = models.FloatField()
	eixo_3_1_e_num = models.FloatField()
	eixo_3_1_f_num = models.FloatField()
	eixo_3_1_g_num = models.FloatField()
	eixo_3_1_h_num = models.FloatField()

	# pontos por participacao
	eixo_3_1_a_pontos = models.FloatField()
	eixo_3_1_b_pontos = models.FloatField()
	eixo_3_1_c_pontos = models.FloatField()
	eixo_3_1_d_pontos = models.FloatField()
	eixo_3_1_e_pontos = models.FloatField()
	eixo_3_1_f_pontos = models.FloatField()
	eixo_3_1_g_pontos = models.FloatField()
	eixo_3_1_h_pontos = models.FloatField()

	# total
	eixo_3_1_a_total = models.FloatField()
	eixo_3_1_b_total = models.FloatField()
	eixo_3_1_c_total = models.FloatField()
	eixo_3_1_d_total = models.FloatField()
	eixo_3_1_e_total = models.FloatField()
	eixo_3_1_f_total = models.FloatField()
	eixo_3_1_g_total = models.FloatField()
	eixo_3_1_h_total = models.FloatField()

	# justificativa / comentario
	eixo_3_justificacao_comentario = models.TextField()

	### INICIO EIXO 4.1 ###
	# atividades de pesquisa e inovacao tecnologica
	# projeto de pesquisa e desenvolvimento tecnologico

	# numero
	eixo_4_1_a_num = models.FloatField()
	eixo_4_1_b_num = models.FloatField()
	eixo_4_1_c_num = models.FloatField()
	eixo_4_1_d_num = models.FloatField()

	# pontos
	eixo_4_1_a_pontos = models.FloatField()
	eixo_4_1_b_pontos = models.FloatField()
	eixo_4_1_c_pontos = models.FloatField()
	eixo_4_1_d_pontos = models.FloatField()

	# total
	eixo_4_1_a_total = models.FloatField()
	eixo_4_1_b_total = models.FloatField()
	eixo_4_1_c_total = models.FloatField()
	eixo_4_1_d_total = models.FloatField()

	### INICIO EIXO 4.2 ###
	# producao bibliografica

	# numero
	eixo_4_2_a_num = models.FloatField()
	eixo_4_2_b_num = models.FloatField()
	eixo_4_2_c_num = models.FloatField()
	eixo_4_2_d_num = models.FloatField()
	eixo_4_2_e_num = models.FloatField()
	eixo_4_2_f_num = models.FloatField()
	# valores dentro do codigo f - qualis:
	eixo_4_2_f_A1_num = models.FloatField()
	eixo_4_2_f_A2_num = models.FloatField()
	eixo_4_2_f_B1_num = models.FloatField()
	eixo_4_2_f_B2_num = models.FloatField()
	eixo_4_2_f_B3_num = models.FloatField()
	eixo_4_2_f_B4_num = models.FloatField()
	eixo_4_2_f_B5_num = models.FloatField()
	eixo_4_2_f_C_num = models.FloatField()

	eixo_4_2_g_num = models.FloatField()
	eixo_4_2_h_num = models.FloatField()
	eixo_4_2_i_num = models.FloatField()
	eixo_4_2_j_num = models.FloatField()
	eixo_4_2_k_num = models.FloatField()
	eixo_4_2_l_num = models.FloatField()
	eixo_4_2_m_num = models.FloatField()
	eixo_4_2_n_num = models.FloatField()
	eixo_4_2_o_num = models.FloatField()
	eixo_4_2_p_num = models.FloatField()
	eixo_4_2_q_num = models.FloatField()
	eixo_4_2_r_num = models.FloatField()
	eixo_4_2_s_num = models.FloatField()

	# pontos
	eixo_4_2_a_pontos = models.FloatField()
	eixo_4_2_b_pontos = models.FloatField()
	eixo_4_2_c_pontos = models.FloatField()
	eixo_4_2_d_pontos = models.FloatField()
	eixo_4_2_e_pontos = models.FloatField()
	eixo_4_2_f_pontos = models.FloatField()
	# valores dentro do codigo f - qualis:
	eixo_4_2_f_A1_pontos = models.FloatField()
	eixo_4_2_f_A2_pontos = models.FloatField()
	eixo_4_2_f_B1_pontos = models.FloatField()
	eixo_4_2_f_B2_pontos = models.FloatField()
	eixo_4_2_f_B3_pontos = models.FloatField()
	eixo_4_2_f_B4_pontos = models.FloatField()
	eixo_4_2_f_B5_pontos = models.FloatField()
	eixo_4_2_f_C_pontos = models.FloatField()

	eixo_4_2_g_pontos = models.FloatField()
	eixo_4_2_h_pontos = models.FloatField()
	eixo_4_2_i_pontos = models.FloatField()
	eixo_4_2_j_pontos = models.FloatField()
	eixo_4_2_k_pontos = models.FloatField()
	eixo_4_2_l_pontos = models.FloatField()
	eixo_4_2_m_pontos = models.FloatField()
	eixo_4_2_n_pontos = models.FloatField()
	eixo_4_2_o_pontos = models.FloatField()
	eixo_4_2_p_pontos = models.FloatField()
	eixo_4_2_q_pontos = models.FloatField()
	eixo_4_2_r_pontos = models.FloatField()
	eixo_4_2_s_pontos = models.FloatField()

	# total
	eixo_4_2_a_total = models.FloatField()
	eixo_4_2_b_total = models.FloatField()
	eixo_4_2_c_total = models.FloatField()
	eixo_4_2_d_total = models.FloatField()
	eixo_4_2_e_total = models.FloatField()
	eixo_4_2_f_total = models.FloatField()
	# valores dentro do codigo f - qualis:
	eixo_4_2_f_A1_total = models.FloatField()
	eixo_4_2_f_A2_total = models.FloatField()
	eixo_4_2_f_B1_total = models.FloatField()
	eixo_4_2_f_B2_total = models.FloatField()
	eixo_4_2_f_B3_total = models.FloatField()
	eixo_4_2_f_B4_total = models.FloatField()
	eixo_4_2_f_B5_total = models.FloatField()
	eixo_4_2_f_C_total = models.FloatField()

	eixo_4_2_g_total = models.FloatField()
	eixo_4_2_h_total = models.FloatField()
	eixo_4_2_i_total = models.FloatField()
	eixo_4_2_j_total = models.FloatField()
	eixo_4_2_k_total = models.FloatField()
	eixo_4_2_l_total = models.FloatField()
	eixo_4_2_m_total = models.FloatField()
	eixo_4_2_n_total = models.FloatField()

SistemaProgressao/forms.py
from django import forms
from .models import *
from django.forms import ModelForm, TextInput

class FormUser(forms.ModelForm):

	first_name = forms.CharField(label='Nome', max_length=30)
	last_name = forms.CharField(label='Sobrenome', max_length=30)
	email = forms.EmailField(label='Email')

	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password']
		widget = {
			'username': TextInput(attrs={'id':'id-username'}),
			'password': TextInput(attrs={'id':'id-password', 'type':'password'}),
		}
		labels = {
			'username': ('SIAPE:'),
			'password': ('Senha:'),
		}
		help_texts = {
			'username': '',
		}
'''
class UsuarioLoginForm(forms.ModelForm):

	password = forms.CharField(widget=forms.PasswordInput())

	# login usuario
	class Meta:
		model = Usuario
		fields = ('email','password',)
		widget = {
			'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength': 254}),
			'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength': 254}),
		}

	def save(self, commit=True):
		usuario = super(UsuarioModelForm, self).save(commit=False)
		usuario.set_password(self.cleaned_data['password'])

		if commit:
			usuario.save()

		return usuario
'''
###
# tudo ok ate aqui
###

class DocumentosForm(forms.ModelForm):

	# envio dos documentos
	class Meta:
		model = Documento
		fields = ('link_pdf',)

class HistoricoForm(forms.ModelForm):

	# historico dos formularios do usuario
	class Meta:
		model = Historico
		fields = ('link_pdf_final',)

# informacoes gerais do usuario para preenchimento dos anexos
class InfoForm(forms.ModelForm):
	class Meta:
		model =  InfoGerais
		fields = ('usuario', 'lotacao', 'classe', 'periodo',)

# definicao dos anexos i, ii, iii, iv
class AnexoIForm(forms.ModelForm):

	# anexo i
	class Meta:
		model = AnexoI
		fields = '__all__'

class AnexoIIForm(forms.ModelForm):

	# anexo ii
	class Meta:
		model = AnexoII
		fields = '__all__'

class AnexoIIIForm(forms.ModelForm):

	# anexo iii
	class Meta:
		model = AnexoIII
		fields = '__all__'

class AnexoIVForm(forms.ModelForm):

	# anexo iv
	class Meta:
		model = AnexoIV
		fields = '__all__'

SistemaProgressao/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect,HttpResponse
from .forms import *

from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

#
# o que tenho que fazer funcionar hoje ainda
# cadastrar e login
#

def cadastrar(request):

	if request.method == 'POST':
		formUser = FormUser(request.POST)

		if formUser.is_valid():
			nome = formUser.cleaned_data['first_name']
			sobrenome = formUser.cleaned_data['last_name']
			siape = formUser.cleaned_data['username']
			email = formUser.cleaned_data['email']
			senha = formUser.cleaned_data['password']
			user = User.objects.create_user(siape, email, senha)
			user.first_name = nome
			user.last_name = sobrenome
			user.save()
			Usuario.objects.create(user=user)
			return HttpResponseRedirect(request.POST.get('next'))

	else:
		formUser = FormUser()

	return render(request, 'SistemaProgressao/cadastrar.html', {'formUser': formUser})


def do_login(request):

	if request.method == 'POST':
		u = authenticate(email=request.POST['email'], password=request.POST['password'])

		if u is not None:
			UsuarioLoginForm(request, u)
			return redirect('/main')

	return render(request, 'SistemaProgressao/login.html')

def do_logout(request):
	logout(request)
	return redirect('/apresentacao')

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Senha alterada com sucesso!')
            return redirect('SistemaProgressao:change_password')
        else:
            messages.error(request, 'Senhas incompatíveis.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'SistemaProgressao/change_password.html', {
        'form': form
    })

# teste acima
# cadastrar refutado
# terminar autenticacao hoje
#

@login_required
def main(request):
	return render(request, 'SistemaProgressao/main.html', {})

# historico de atividade do usuario
@login_required
def historico(request):
	form = HistoricoForm()
	return render(request, 'SistemaProgressao/historico.html', {'form': form})

# anexos a serem preenchidos pelos usuarios
@login_required
def documents(request):
	form = DocumentosForm()
	return render(request, 'SistemaProgressao/documents.html',{'form': form})

@login_required
def infogerais(request):
	form = InfoForm()
	return render(request, 'SistemaProgressao/infogerais.html', {'form': form})

def apresentacao(request):
	form = InfoForm()
	return render(request, 'SistemaProgressao/apresentacao.html', {'form': form})

#
# anexos i, ii, iii, iv
#

@login_required
def anexoi(request):
	form = AnexoIForm()
	return render(request, 'SistemaProgressao/anexoi.html', {'form': form})

@login_required
def anexoii(request):
	form = AnexoIIForm()
	return render(request, 'SistemaProgressao/anexoii.html', {'form': form})

@login_required
def anexoiii(request):
	form = AnexoIIIForm()
	return render(request, 'SistemaProgressao/anexoiii.html', {'form': form})

@login_required
def anexoiv(request):
	form = AnexoIVForm()
	return render(request, 'SistemaProgressao/anexoiv.html', {'form': form})

#
# login e cadastro de usuario
#
'''
# cadastrar usuario
def cadastrar(request):

	# dados passados via post
	if request.method == 'POST':
		form = UsuarioLCadastrarForm(request.POST)

		if form.is_valid():
			# se o formulario for valido, salva-lo
			form.save()
			return HttpResponseRedirect('/login/') # redireciona para o login
		else:
			# manter na pagina caso esteja faltando alguma informacao
			return render(request, 'SistemaProgressao/cadastrar.html', {'form': form })

	# se nenhuma informacao for passado, exibir a pagina de cadastro
	return render(request, 'SistemaProgressao/cadastrar.html', {'form': UsuarioLCadastrarForm() })
'''

SistemaProgressao/templates/SistemaProgressao/anexoi.html
{% extends 'SistemaProgressao/main.html' %}

<html>
<head>
	<title>Sistema Progressao - Anexo I</title>
</head>

<body>
	{% block content %}
	<h2>Sistema Progressao</h2>

	<form method="POST">
		{% csrf_token %}

		<div class="container-fluid">
			<h4>1. Eixo 1 - Avaliação Discente</h4>
			<div class="col-xs-2">

			</div>
			<br>
			<div class="col-xs-4">
				Pontuação do Eixo
			</div>
			<div class="col-xs-2">
				Máximo 40 pontos
			</div>
			<div class="col-xs-2">
				Total
				{{ form.eixo_1 }}
			</div>
			<div class="col-xs-2">
				Jusficativa / Comentário
				{{ form.eixo_1_justificacao_comentario }}
			</div>
		</div>

		<div class="container-fluid">
			<h4>2. Eixo 2.1 - Ensino Convencional</h4>
			<div class="col-xs-2">
				Código
			</div>
			<br>
			<div class="col-xs-4">
				Carga horária de ensino semanal
			</div>
			<div class="col-xs-2">
				Horas de aula (média do per)/semana
				{{ form.eixo_2_1_a_hora }}
			</div>
			<div class="col-xs-2">
				Pontos por hora de aula por semana
				{{ form.eixo_2_1_a_pontos }}
			</div>
			<div class="col-xs-2">
				Total
				{{ form.eixo_2_1_a_total }}
			</div>
		</div>
		{{ form.as_p }}

	</form>
	{% endblock content %}

</body>

</html>

SistemaProgressao/templates/SistemaProgressao/anexoii.html
{% extends 'SistemaProgressao/main.html' %}
<html>
<head>
	<title>Sistema Progressao - Anexo II</title>
</head>

<body>
{% block content %}
<h2>Sistema Progressao</h2>
	<form method="POST">
		{% csrf_token %}
	    
		{{ form.as_p }}
	</form>
</body>
{% endblock content %}
</html>

SistemaProgressao/templates/SistemaProgressao/anexoiii.html
{% extends 'SistemaProgressao/main.html' %}
<html>
<head>
	<title>Sistema Progressao - Anexo III</title>
</head>

<body>
{% block content %}
<h2>Sistema Progressao</h2>
	<form method="POST">
		{% csrf_token %}
	    
		{{ form.as_p }}
	</form>
</body>
{% endblock content %}
</html>

SistemaProgressao/templates/SistemaProgressao/anexoiv.html
{% extends 'SistemaProgressao/main.html' %}
<html>
<head>
	<title>Sistema Progressao - Anexo IV</title>
</head>

<body>
{% block content %}
<h2>Sistema Progressao</h2>
	<form method="POST">
		{% csrf_token %}
	    
		{{ form.as_p }}
	</form>
</body>
{% endblock content %}
</html>

SistemaProgressao/templates/SistemaProgressao/cadastrar.html
<html>
<head>
	<title>Sistema Progressao - Cadastrar usuario</title>
</head>

<body>
<h2>Sistema Progressao</h2>
	<form action="{% url 'SistemaProgressao:cadastrar' %}" method="POST">
		{% csrf_token %}

		{{ formUser.as_p }}

		<input type='submit' value='Cadastrar'>
	</form>
</body>
</html>

SistemaProgressao/templates/SistemaProgressao/change_password.html
<html>
<head>
	<title>Sistema Progressao - Alterar senha</title>
</head>

<body>
<h2>Sistema Progressao</h2>
<form method="post" action="{% url 'SistemaProgressao:change_password' %}">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Salvar nova senha</button>
</form>
</body>
</html>

SistemaProgressao/templates/SistemaProgressao/documents.html
<html>
<head>
	<title>Sistema Progressao - Documentos</title>
</head>

<body>
<h2>Sistema Progressao</h2>
	<form method="POST">
		{% csrf_token %}
	    
		{{ form.as_p }}
	</form>
</body>
</html>

SistemaProgressao/templates/SistemaProgressao/historico.html
<html>
<head>
	<title>Sistema Progressao - Histórico</title>
</head>

<body>
<h2>Sistema Progressao</h2>
	<form method="POST">
		{% csrf_token %}
	    
		{{ form.as_p }}
	</form>
</body>
</html>

SistemaProgressao/templates/SistemaProgressao/infogerias.html
<html>
<head>
	<title>Sistema Progressao - Cadastrar usuário</title>
</head>

<body>
<h2>Sistema Progressao</h2>
	<form method="POST">
		{% csrf_token %}
	    
		{{ form.as_p }}
	    
		<input type='submit' value='Cadastrar'>
	</form>
</body>
</html>

SistemaProgressao/templates/SistemaProgressao/login.html
<html>
<head>
	<title>Sistema Progressao - Log in</title>
</head>

<body>
<h2>Sistema Progressao</h2>
	<form method="post" action="{% url 'SistemaProgressao:login' %}">
		{% csrf_token %}

		Email <br>
		<input type="text" name="email"> <br>
		Password <br>
		<input type="password" name="password"> <br>

		<input type='submit' value='Entrar'>
	</form>
</body>
</html>

SistemaProgressao/templates/SistemaProgressao/main.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title>Bem-vindo ao Sistema Progress&atilde;o</title>
	<meta charset = 'utf-8'>
	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i||Ubuntu:300,400,500,700">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
	<header class="main-header header-attribute" style="background-image: url({% static '/image/header-background.png' %});">

		<div>

			<img class="avatar-shape" src="{% static '/image/Avatar-Shape.png' %}">

			<h1>
				<span style="font-size: 26px;">Bem-vindo,</span> <br>
				<a href=""><span> {{ Usuario.username }} </span></a>
			</h1>

			<nav>
				<img class="prisma-logo-image" style="width: 31px; height: 40px; margin-top: -10%; margin-right: 5px;" src="{% static '/image/PRISMA_logo.png' %}">
				<span class="prisma-logo-text" style="font-size: 26px;" href="#">prisma</span> <br>

				<div align="right">
					<a href="{% url 'SistemaProgressao:change_password' %}">Alterar senha</a><br>
					<a href="{% url 'SistemaProgressao:logout' %}">Log Out</a>
				</div>

			</nav>

		</div>

	</header>

	<div>

		<header class="main-header tool-bar">

			<img class="logo-ifes-image" src="{% static '/image/IFES_logo.png' %}">

			<a href="/anexoi">Anexo I</a>
			<a href="/anexoii">Anexo II</a>
			<a href="/anexoiii">Anexo III</a>
			<a href="/anexoiv">Anexo IV</a>

			<a href="/historico">Histórico</a>

			<nav>

				<img class="add-icon" src="{% static '/image/Add File.png' %}">

			</nav>

		</header>

	</div>

	{% block content %}
  {% endblock %}

</body>
</html>